services:
  db_blog:
    image: postgres:latest
    container_name: blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: turizamSifra
      POSTGRES_DB: blog_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  blog:
    build: 
      context: ./backend/blog
    container_name: blog-service
    ports:
      - 8081:8081
    depends_on:
      - db_blog
    environment:
      DB_URL: "host=db_blog user=postgres password=turizamSifra dbname=blog_db port=5432 sslmode=disable"
    volumes:
      - ./uploads:/root/uploads
    
volumes:
  postgres_data:

    