events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        # Stakeholders / Auth servis (port 8082)
        location /api/auth {
            proxy_pass http://stakeholders:8082;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/users {
            proxy_pass http://stakeholders:8082;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Blog servis (port 8081)
        location /blogs {
            proxy_pass http://blog:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Followers servis (port 8000)
        location /api/followers {
            proxy_pass http://followers:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Tours servis (port 8083)
        location /api/tours {
            proxy_pass http://tours:8083;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/position {
            proxy_pass http://tours:8083;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Purchase servis (port 8084)
        location /api/purchase {
            proxy_pass http://purchase:8084;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}