// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: checkout.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type PurchaseToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TouristId     int64                  `protobuf:"varint,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,3,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,4,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseToken) Reset() {
	*x = PurchaseToken{}
	mi := &file_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseToken) ProtoMessage() {}

func (x *PurchaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseToken.ProtoReflect.Descriptor instead.
func (*PurchaseToken) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseToken) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PurchaseToken) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *PurchaseToken) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PurchaseToken) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *PurchaseToken) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tokens        []*PurchaseToken       `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *CheckoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckoutResponse) GetTokens() []*PurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_checkout_proto protoreflect.FileDescriptor

const file_checkout_proto_rawDesc = "" +
	"\n" +
	"\x0echeckout.proto\x12\bpurchase\"0\n" +
	"\x0fCheckoutRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\x03R\ttouristId\"\x93\x01\n" +
	"\rPurchaseToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\x03R\ttouristId\x12\x17\n" +
	"\atour_id\x18\x03 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x04 \x01(\tR\btourName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"]\n" +
	"\x10CheckoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x06tokens\x18\x02 \x03(\v2\x17.purchase.PurchaseTokenR\x06tokens2T\n" +
	"\x0fCheckoutService\x12A\n" +
	"\bCheckout\x12\x19.purchase.CheckoutRequest\x1a\x1a.purchase.CheckoutResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_checkout_proto_rawDescOnce sync.Once
	file_checkout_proto_rawDescData []byte
)

func file_checkout_proto_rawDescGZIP() []byte {
	file_checkout_proto_rawDescOnce.Do(func() {
		file_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)))
	})
	return file_checkout_proto_rawDescData
}

var file_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_checkout_proto_goTypes = []any{
	(*CheckoutRequest)(nil),  // 0: purchase.CheckoutRequest
	(*PurchaseToken)(nil),    // 1: purchase.PurchaseToken
	(*CheckoutResponse)(nil), // 2: purchase.CheckoutResponse
}
var file_checkout_proto_depIdxs = []int32{
	1, // 0: purchase.CheckoutResponse.tokens:type_name -> purchase.PurchaseToken
	0, // 1: purchase.CheckoutService.Checkout:input_type -> purchase.CheckoutRequest
	2, // 2: purchase.CheckoutService.Checkout:output_type -> purchase.CheckoutResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_checkout_proto_init() }
func file_checkout_proto_init() {
	if File_checkout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkout_proto_rawDesc), len(file_checkout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_proto_goTypes,
		DependencyIndexes: file_checkout_proto_depIdxs,
		MessageInfos:      file_checkout_proto_msgTypes,
	}.Build()
	File_checkout_proto = out.File
	file_checkout_proto_goTypes = nil
	file_checkout_proto_depIdxs = nil
}
