// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: tour_check.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourCheckRequest) Reset() {
	*x = TourCheckRequest{}
	mi := &file_tour_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourCheckRequest) ProtoMessage() {}

func (x *TourCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourCheckRequest.ProtoReflect.Descriptor instead.
func (*TourCheckRequest) Descriptor() ([]byte, []int) {
	return file_tour_check_proto_rawDescGZIP(), []int{0}
}

func (x *TourCheckRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type TourCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourCheckResponse) Reset() {
	*x = TourCheckResponse{}
	mi := &file_tour_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourCheckResponse) ProtoMessage() {}

func (x *TourCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourCheckResponse.ProtoReflect.Descriptor instead.
func (*TourCheckResponse) Descriptor() ([]byte, []int) {
	return file_tour_check_proto_rawDescGZIP(), []int{1}
}

func (x *TourCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourCheckResponse) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *TourCheckResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_tour_check_proto protoreflect.FileDescriptor

const file_tour_check_proto_rawDesc = "" +
	"\n" +
	"\x10tour_check.proto\x12\x05tours\"+\n" +
	"\x10TourCheckRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"^\n" +
	"\x11TourCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price2R\n" +
	"\x10TourCheckService\x12>\n" +
	"\tCheckTour\x12\x17.tours.TourCheckRequest\x1a\x18.tours.TourCheckResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_tour_check_proto_rawDescOnce sync.Once
	file_tour_check_proto_rawDescData []byte
)

func file_tour_check_proto_rawDescGZIP() []byte {
	file_tour_check_proto_rawDescOnce.Do(func() {
		file_tour_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_check_proto_rawDesc), len(file_tour_check_proto_rawDesc)))
	})
	return file_tour_check_proto_rawDescData
}

var file_tour_check_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tour_check_proto_goTypes = []any{
	(*TourCheckRequest)(nil),  // 0: tours.TourCheckRequest
	(*TourCheckResponse)(nil), // 1: tours.TourCheckResponse
}
var file_tour_check_proto_depIdxs = []int32{
	0, // 0: tours.TourCheckService.CheckTour:input_type -> tours.TourCheckRequest
	1, // 1: tours.TourCheckService.CheckTour:output_type -> tours.TourCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tour_check_proto_init() }
func file_tour_check_proto_init() {
	if File_tour_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_check_proto_rawDesc), len(file_tour_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_check_proto_goTypes,
		DependencyIndexes: file_tour_check_proto_depIdxs,
		MessageInfos:      file_tour_check_proto_msgTypes,
	}.Build()
	File_tour_check_proto = out.File
	file_tour_check_proto_goTypes = nil
	file_tour_check_proto_depIdxs = nil
}
