// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: tour_check.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourCheckService_CheckTour_FullMethodName = "/tours.TourCheckService/CheckTour"
)

// TourCheckServiceClient is the client API for TourCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourCheckServiceClient interface {
	CheckTour(ctx context.Context, in *TourCheckRequest, opts ...grpc.CallOption) (*TourCheckResponse, error)
}

type tourCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourCheckServiceClient(cc grpc.ClientConnInterface) TourCheckServiceClient {
	return &tourCheckServiceClient{cc}
}

func (c *tourCheckServiceClient) CheckTour(ctx context.Context, in *TourCheckRequest, opts ...grpc.CallOption) (*TourCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourCheckResponse)
	err := c.cc.Invoke(ctx, TourCheckService_CheckTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourCheckServiceServer is the server API for TourCheckService service.
// All implementations must embed UnimplementedTourCheckServiceServer
// for forward compatibility.
type TourCheckServiceServer interface {
	CheckTour(context.Context, *TourCheckRequest) (*TourCheckResponse, error)
	mustEmbedUnimplementedTourCheckServiceServer()
}

// UnimplementedTourCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourCheckServiceServer struct{}

func (UnimplementedTourCheckServiceServer) CheckTour(context.Context, *TourCheckRequest) (*TourCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTour not implemented")
}
func (UnimplementedTourCheckServiceServer) mustEmbedUnimplementedTourCheckServiceServer() {}
func (UnimplementedTourCheckServiceServer) testEmbeddedByValue()                          {}

// UnsafeTourCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourCheckServiceServer will
// result in compilation errors.
type UnsafeTourCheckServiceServer interface {
	mustEmbedUnimplementedTourCheckServiceServer()
}

func RegisterTourCheckServiceServer(s grpc.ServiceRegistrar, srv TourCheckServiceServer) {
	// If the following call panics, it indicates UnimplementedTourCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourCheckService_ServiceDesc, srv)
}

func _TourCheckService_CheckTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourCheckServiceServer).CheckTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourCheckService_CheckTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourCheckServiceServer).CheckTour(ctx, req.(*TourCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourCheckService_ServiceDesc is the grpc.ServiceDesc for TourCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tours.TourCheckService",
	HandlerType: (*TourCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTour",
			Handler:    _TourCheckService_CheckTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour_check.proto",
}
