{
 "title": "Container Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"cadvisor\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{job=\"cadvisor\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{job=\"cadvisor\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}