// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proximity.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	ProximityService_CheckProximity_FullMethodName = "/proximity.ProximityService/CheckProximity"
)

type ProximityServiceClient interface {
	CheckProximity(ctx context.Context, in *ProximityRequest, opts ...grpc.CallOption) (*ProximityResponse, error)
}

type proximityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProximityServiceClient(cc grpc.ClientConnInterface) ProximityServiceClient {
	return &proximityServiceClient{cc}
}

func (c *proximityServiceClient) CheckProximity(ctx context.Context, in *ProximityRequest, opts ...grpc.CallOption) (*ProximityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProximityResponse)
	err := c.cc.Invoke(ctx, ProximityService_CheckProximity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type ProximityServiceServer interface {
	CheckProximity(context.Context, *ProximityRequest) (*ProximityResponse, error)
	mustEmbedUnimplementedProximityServiceServer()
}

type UnimplementedProximityServiceServer struct{}

func (UnimplementedProximityServiceServer) CheckProximity(context.Context, *ProximityRequest) (*ProximityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckProximity not implemented")
}
func (UnimplementedProximityServiceServer) mustEmbedUnimplementedProximityServiceServer() {}
func (UnimplementedProximityServiceServer) testEmbeddedByValue()                           {}

type UnsafeProximityServiceServer interface {
	mustEmbedUnimplementedProximityServiceServer()
}

func RegisterProximityServiceServer(s grpc.ServiceRegistrar, srv ProximityServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProximityService_ServiceDesc, srv)
}

func _ProximityService_CheckProximity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProximityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProximityServiceServer).CheckProximity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProximityService_CheckProximity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProximityServiceServer).CheckProximity(ctx, req.(*ProximityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ProximityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proximity.ProximityService",
	HandlerType: (*ProximityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckProximity",
			Handler:    _ProximityService_CheckProximity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proximity.proto",
}