// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proximity.proto

package pb

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type ProximityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TouristId     int64                  `protobuf:"varint,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProximityRequest) Reset()         { *x = ProximityRequest{} }
func (x *ProximityRequest) String() string { return x.ExecutionId }
func (x *ProximityRequest) ProtoMessage()  {}

func (x *ProximityRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ProximityRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *ProximityRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ProximityRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type ProximityResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId        string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastActivity       string                 `protobuf:"bytes,3,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	CompletedKeyPoints []*CompletedKeyPoint   `protobuf:"bytes,4,rep,name=completed_key_points,json=completedKeyPoints,proto3" json:"completed_key_points,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProximityResponse) Reset()         { *x = ProximityResponse{} }
func (x *ProximityResponse) String() string { return x.ExecutionId }
func (x *ProximityResponse) ProtoMessage()  {}

func (x *ProximityResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ProximityResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProximityResponse) GetLastActivity() string {
	if x != nil {
		return x.LastActivity
	}
	return ""
}

func (x *ProximityResponse) GetCompletedKeyPoints() []*CompletedKeyPoint {
	if x != nil {
		return x.CompletedKeyPoints
	}
	return nil
}

type CompletedKeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index"`
	CompletedAt   string                 `protobuf:"bytes,2,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedKeyPoint) Reset()         { *x = CompletedKeyPoint{} }
func (x *CompletedKeyPoint) String() string { return x.CompletedAt }
func (x *CompletedKeyPoint) ProtoMessage()  {}

func (x *CompletedKeyPoint) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CompletedKeyPoint) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}